[package]
name = "perf_client"
version = "0.1.0"
authors = ["Ryo Ohki <roki.swindler@gmail.com>"]
build = "build.rs"

[dependencies]
widestring = "0.2.2"
winapi = "0.2.8"
serde = "0.8"
serde_json = "0.8"
hyper = "0.8"

[dependencies.pdh-sys]
path = "../winapi-rs/lib/pdh"
